/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import Lib.XFile;
import Login.Login;
import Model.Phone;
import java.awt.CardLayout;
import java.awt.Color;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Locale;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class Phone_shop extends javax.swing.JFrame {

    CardLayout cardLayout;
    Map<String,String> menu;
    JFrame frontScreen;
    DefaultTableModel tbModel;
    String filePath = "";
    ArrayList<Phone> PhoneList;
    int currentRow = -1; 
    byte b = 1;
    DefaultComboBoxModel cbModel = new DefaultComboBoxModel();
//    Locale locale = new Locale("en", "EN");
//    String pattern = "###,###.##";
    
    public Phone_shop(String name,Login aThis) {
        initComponents();
        initTable();
        loadCb();
        
        frontScreen = aThis;
        cardLayout = (CardLayout) Phone_Management.getLayout();
        
        tbPhone.setDefaultEditor(Object.class, null);
        
        filePath = "./src/lib/Phone.dat";
        PhoneList = new ArrayList<>();
        
        boolean file = loadFile(); 
        if(file){  
            fillToTable();   
        }else{      
            JOptionPane.showMessageDialog(this,"Nothing to show u");
        }
             
        this.setLocationRelativeTo(null);
    }
    /**
     * Creates new form Welcome
     */
    public Phone_shop() {
        initComponents(); 
    }
   
    private void initTable(){
        String[] columnNames = {"Phone ID","Name","Brand","Quantity","Color","Price"};
        
        tbModel = new DefaultTableModel(columnNames,0);
        tbPhone.setModel(tbModel);
    }
    private void fillToTable(){
        tbModel.setRowCount(0); 
        
//        DecimalFormat decimalFormat = (DecimalFormat)NumberFormat.getNumberInstance(locale);
//        decimalFormat.applyPattern(pattern); 
        
        for (Phone c : PhoneList) {
            Object[] row = new Object[]{c.getPhone_ID(),
                c.getName(),c.getBrand(),c.getQuantity(),c.getPColor(),c.getPrice()};
            tbModel.addRow(row);
        }
    }
           
    private boolean loadFile(){
        if(XFile.readObject(filePath) == null){ 
            return false;   
        }
        PhoneList = (ArrayList<Phone>) XFile.readObject(filePath);  
        return true;
    }
    
    private void loadCb(){
        String[] brandList = {"Phone Brand","Samsung","Apple","ASUS","Vivo","OPPO"};
        
        for (String string : brandList) {
            cbModel.addElement(string);
        }
        cbBrand.setModel(cbModel);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Phone_Management = new javax.swing.JPanel();
        Manage = new javax.swing.JPanel();
        Tittle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        cbBrand = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        Refresh = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPhone = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Phone_Management.setBackground(new java.awt.Color(255, 255, 255));
        Phone_Management.setLayout(new java.awt.CardLayout());

        Tittle.setBackground(new java.awt.Color(255, 255, 255));
        Tittle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Tittle.setForeground(new java.awt.Color(51, 51, 255));
        Tittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tittle.setText("Phone Management");
        Tittle.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Tittle.setFocusable(false);
        Tittle.setOpaque(true);
        Tittle.setVerifyInputWhenFocusTarget(false);

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Phone_ID:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Name:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Brand:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Price:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Quantity:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Color:");

        txtName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 255)));
        txtName.setOpaque(true);
        txtName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNameMouseClicked(evt);
            }
        });

        txtID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 255)));
        txtID.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtID.setOpaque(true);
        txtID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIDMouseClicked(evt);
            }
        });

        txtPrice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 255)));
        txtPrice.setOpaque(true);
        txtPrice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPriceMouseClicked(evt);
            }
        });

        txtQuantity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 255)));
        txtQuantity.setOpaque(true);
        txtQuantity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtQuantityMouseClicked(evt);
            }
        });

        txtColor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 255)));
        txtColor.setOpaque(true);
        txtColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtColorMouseClicked(evt);
            }
        });

        cbBrand.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(txtID)
                    .addComponent(cbBrand, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        Refresh.setForeground(new java.awt.Color(51, 51, 255));
        Refresh.setText("Refresh");
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });
        jPanel2.add(Refresh);

        Add.setBackground(new java.awt.Color(51, 255, 51));
        Add.setForeground(new java.awt.Color(255, 255, 255));
        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        jPanel2.add(Add);

        Update.setBackground(new java.awt.Color(51, 51, 255));
        Update.setForeground(new java.awt.Color(255, 255, 255));
        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        jPanel2.add(Update);

        Delete.setBackground(new java.awt.Color(255, 0, 0));
        Delete.setForeground(new java.awt.Color(255, 255, 255));
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jPanel2.add(Delete);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        tbPhone.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbPhone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbPhoneMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbPhone);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout ManageLayout = new javax.swing.GroupLayout(Manage);
        Manage.setLayout(ManageLayout);
        ManageLayout.setHorizontalGroup(
            ManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tittle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ManageLayout.setVerticalGroup(
            ManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageLayout.createSequentialGroup()
                .addComponent(Tittle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Phone_Management.add(Manage, "manage");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Phone_Management, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Phone_Management, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        // TODO add your handling code here:
        resetForm();
        fillToTable();
    }//GEN-LAST:event_RefreshActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
        addPhone();
        fillToTable();
        saveFile();
    }//GEN-LAST:event_AddActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        if(currentRow > -1){
            updatePhone();
            fillToTable();
            saveFile();
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        if(currentRow != -1){
            deletePhone();
            fillToTable();
            saveFile();
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void tbPhoneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPhoneMousePressed
        // TODO add your handling code here:
        txtID.setEnabled(false);  // vô hiệu hoá việc người dùng chỉnh sửa ID
        currentRow = tbPhone.getSelectedRow();
        showDetail(currentRow);
    }//GEN-LAST:event_tbPhoneMousePressed

    private void txtIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIDMouseClicked
        // TODO add your handling code here:
        txtID.setEnabled(true);
        if( b == 0){
        txtID.setText("");
        txtID.setForeground(Color.black);
        b = 1;
        }
    }//GEN-LAST:event_txtIDMouseClicked

    private void txtNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNameMouseClicked
        // TODO add your handling code here:
        if( b == 0){
        txtName.setText("");
        txtName.setForeground(Color.black);
        b = 1;
        }
    }//GEN-LAST:event_txtNameMouseClicked

    private void txtQuantityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtQuantityMouseClicked
        // TODO add your handling code here:
        if( b == 0 ){
        txtQuantity.setText("");
        txtQuantity.setForeground(Color.black);
        b = 1;
        }
    }//GEN-LAST:event_txtQuantityMouseClicked

    private void txtColorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtColorMouseClicked
        // TODO add your handling code here:
        if( b == 0 ){
        txtColor.setText("");
        txtColor.setForeground(Color.black);
        b = 1;
        }
    }//GEN-LAST:event_txtColorMouseClicked

    private void txtPriceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPriceMouseClicked
        // TODO add your handling code here:
        if( b == 0 ){
        txtPrice.setText("");
        txtPrice.setForeground(Color.black);
        b = 1;
        }
    }//GEN-LAST:event_txtPriceMouseClicked
 
     private void showDetail(int r){
         
        String id = (String) tbPhone.getValueAt(r,0); 
        txtID.setText(id);
        
        String name = (String) tbPhone.getValueAt(r, 1);
        txtName.setText(name);
        
        String Brand = (String) tbPhone.getValueAt(r, 2);
        cbBrand.setSelectedItem(Brand);
        
        Integer Quantity = (Integer) tbPhone.getValueAt(r, 3);
        txtQuantity.setText(Quantity.toString());
        
        String PColor = (String) tbPhone.getValueAt(r, 4);
        txtColor.setText(PColor);
        
        Double Price = (Double) tbPhone.getValueAt(r, 5);
        txtPrice.setText(Price.toString());      
    }
 
    private void resetForm(){
        txtID.setEnabled(true);
        txtID.setText(null);
        txtName.setText(null);
        txtPrice.setText(null);
        cbBrand.setSelectedIndex(0);
        txtColor.setText(null);
        txtQuantity.setText(null);
    }
    
    private void deletePhone(){
        
        if(currentRow == -1){
            JOptionPane.showMessageDialog(this," Nothing left to delete");
            return;
        }
        
        int result = JOptionPane.showConfirmDialog(this,
                "Do you wanna delete this?", "Delete row",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );
 
        if(result == JOptionPane.YES_OPTION){
            PhoneList.remove(currentRow);
            resetForm();
            return ;
        } 
    }
    
    private void updatePhone(){
        Phone p = PhoneList.get(currentRow); 

    p.setPhone_ID(txtID.getText());
    p.setName(txtName.getText());
    p.setBrand(cbBrand.getSelectedItem().toString());
    p.setQuantity(Integer.parseInt(txtQuantity.getText()));
    p.setPColor(txtColor.getText());
    p.setPrice(Double.parseDouble(txtPrice.getText()));  
    
    }
    
    private void addPhone(){
        
        String Id = txtID.getText();
        if (Id.equals("") || (b == 0) || (Id.equals("Enter ID please")) 
                || (Id.equals("This ID already has been used"))) {
            txtID.setText("Enter ID please");
            txtID.setForeground(Color.red);
            b = 0;
            return;
        }
        
        for (Phone phone : PhoneList) {
            if(Id.equals(phone.getPhone_ID()) || (b == 0)){
                txtID.setText("This ID already has been used");
                txtID.setForeground(Color.red);
                b = 0;
                return;
            }
        }
        
        String Name = txtName.getText();
        if(Name.equals("") || (b == 0) || (Name.equals("Enter name please"))){
            txtName.setText("Enter name please");
            txtName.setForeground(Color.red);
            b = 0;
            return;
        }
           
        String Brand = cbBrand.getSelectedItem().toString();
        if(cbBrand.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this,"Please choose a phone brand");
            return;
        }
        
        Integer Quantity = Integer.parseInt(txtQuantity.getText());
        if(Quantity < 0 || txtQuantity.getText().equals("") || (b == 0)){
            txtPrice.setText("Quantity must greater than zero ");
            txtPrice.setForeground(Color.red);
            b = 0;
            return;
        }
        
        String PColor = txtColor.getText();
        if(PColor.equals("") || (b == 0) || (PColor.equals("Enter color please"))){
            txtColor.setText("Enter color please");
            txtColor.setForeground(Color.red);
            b = 0;
            return;
        }
            
        Double Price = Double.parseDouble(txtPrice.getText());
        if(Price < 0 || txtPrice.getText().equals("") || (b == 0)){
            txtPrice.setText("Price must greater than zero ");
            txtPrice.setForeground(Color.red);
            b = 0;
            return;
        }
        
        Phone p = new Phone(Id, Name, Brand, Quantity, PColor, Price );
        PhoneList.add(p);     
    }
    
    private void saveFile(){
        XFile.writeObject(filePath, PhoneList);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Phone_shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Phone_shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Phone_shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Phone_shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Phone_shop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Delete;
    private javax.swing.JPanel Manage;
    private javax.swing.JPanel Phone_Management;
    private javax.swing.JButton Refresh;
    private javax.swing.JLabel Tittle;
    private javax.swing.JButton Update;
    private javax.swing.JComboBox<String> cbBrand;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbPhone;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
